#!/bin/bash

# created by fredericlopesgoncalvesmagalhaes
# @copyright Frederic Lopes Goncalves Magalhaes 2017

openssl genrsa -out private-key.pem 2048
openssl req -new -key private-key.pem -out csr.pem
openssl x509 -req -days 9999 -in csr.pem -signkey private-key.pem -out public-cert.pem
rm csr.pem